apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voxtral-model-storage
  namespace: opentts
  labels:
    app.kubernetes.io/name: voxtral-server
    app.kubernetes.io/part-of: voxtral-server
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
